### ISSUE TITLE
Code & Dataset

### ISSUE THREAD

**Issue by got69** [abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#1]
Hi,
Great work on Urdu OCR, @abdur75648!
It would be great if you tell when will all the codes & datasets mentioned in the UTRNet paper be released?
Thanks in advance

**Comment by abdur75648** [comment]
It'll be released by the end of Aug 2023, after the ICDAR conference presentation.
Thanks for your interest.

**Comment by abdur75648** [comment]
The code & datasets have been released
