### ISSUE TITLE
Clarification regarding the code used for UTRNet

### ISSUE THREAD

**Issue by user94786** [abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#2]
As mentioned in the repo's description and the paper [UTRNet: High-Resolution Urdu Text Recognition In Printed Documents](https://arxiv.org/abs/2306.15782), is the implementation same as the following code:
https://github.com/clovaai/deep-text-recognition-benchmark

Since the code isn't released yet, it would be great if you could share some details on exactly what changes were made so that I can implement it on my own?

**Comment by abdur75648** [comment]
It's built upon the same framework, but our code base has several modifications, which are well described in the paper. The full codebase will be released after the ICDAR conference presentation (last week of Aug 2023).

**Comment by abdur75648** [comment]
The code & datasets have been released
