### ISSUE TITLE
The used Synthetic text dataset

### ISSUE THREAD

**Issue by zobeirraisi** [abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#3]
Thanks for the excellent work and sharing the code. How the synthetic text are prepared (the one that you created) ?  Is it possible to share the code of that, so we also can create for other language.

**Comment by abdur75648** [comment]
Hi @zobeirraisi,
Thank you for your interest in our work.

As mentioned in [this section](https://github.com/abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#synthetic-data-generation-using-urdu-synth-supplementary), we have released the synthetic data generation module publicly as [Urdu-Synth](https://github.com/abdur75648/urdu-synth/).

**Comment by abdur75648** [comment]
Closing this as resolved ✅
