### ISSUE TITLE
Issue with pip install -r requirements.txtpip install -r requirements.txt

### ISSUE THREAD

**Issue by fahimish** [abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#4]
I have tried many times.. But this is where I get stuck.
I have checked !apt-get install git-lfs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git-lfs is already the newest version (3.0.2-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
**ISSUE**
Using cached opencv-contrib-python-4.5.1.48.tar.gz (148.8 MB)
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by fahimish** [comment]
Oh.. and I forgot to mention. I am using COLAB

**Comment by abdur75648** [comment]
Seem to be some issue with Colab - Sadly, the upgrades in Colab environment often cause compatibility issues with old versions of libraries. 
You may try higher versions like 4.5.4.58 (I just tested it's working)

**Comment by abdur75648** [comment]
Closing this as resolved ✅
Demo Colab (Working as of 19/07/2024) - https://colab.research.google.com/drive/1cxctKu_geFjfm8wptDBIPwbhWPO2_7EY
