### ISSUE TITLE
Issue in read.py 

### ISSUE THREAD

**Issue by JehanzaibJ** [abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition#6]
Hello,
Thankyou for the code. I have tried to run this line to read image and get output in a .txt file, but I didnt get any text urdu output.

`CUDA_VISIBLE_DEVICES=0 python3 read.py --image_path path/to/image.png --FeatureExtraction HRNet --SequenceModeling DBiLSTM --Prediction CTC  --saved_model saved_models/UTRNet-Large/best_norm_ED.pth`

This is the output I received:
```

CUDA_VISIBLE_DEVICES=0 python3 read.py --image_path images/page_2.png --FeatureExtraction HRNet --SequenceModeling DBiLSTM --Prediction CTC  --saved_model saved_models/best_norm_ED.pth
Device :  cuda
model input parameters 32 400 20 1 32 256 182 100 HRNet DBiLSTM CTC
Loaded pretrained model from saved_models/best_norm_ED.pth
5
```

**Comment by YaqoobIlyas** [comment]
@JehanzaibJ 
Hi there,
can you please tell me how you have run this project, as I am getting the below error:
<img width="1690" alt="error" src="https://github.com/abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition/assets/95971816/e1b86f27-dc80-4253-87b9-5fcf9ef199ee">

**Comment by Bilal143260** [comment]
@JehanzaibJ I am having the same issue. Were you able to find any solution?

**Comment by YaqoobIlyas** [comment]
nope

**Comment by abdur75648** [comment]
Hi @YaqoobIlyas, I just checked it's working.
You can also try this simple Colab Demo (Working as of 19/07/2024) - https://colab.research.google.com/drive/1cxctKu_geFjfm8wptDBIPwbhWPO2_7EY

**Comment by Bilal143260** [comment]
![image (43)](https://github.com/user-attachments/assets/dc58189c-0b7c-454f-b019-006a63109fd3)

It never works on custom images

**Comment by abdur75648** [comment]
Dear @Bilal143260 - It's not about 'custom images'. It's about printed vs hand-written!
The title of our paper is High-Resolution Urdu Text Recognition In "Printed" Documents.
Hope this explains.
